Server:
  port: 25680

mongodb:
  encrypted-uri: "{cipher}a517cc0cd2e3d64f9a4a9ae03d15743aab0aca07131f9aebe85219010a2d50ff78e4590f7da8bcd516bbc04e3da3fa7d04dfb32012c7a01d4a5f92b18950122b178f28943790e0eda5eb9e14f0b05013"
  qua_util: "/local_qua_util?authSource=admin"
  qua_contest: "/local_qua_contest?authSource=admin"

spring:
  application:
    name: batch-service

  dataSource:
    contest:
      url: jdbc:mysql://qua-rdb/contest_db
      username: "{cipher}876532613553ec861fdad2a10e7f4be2682e0845b8513d2ed09f5b9f34f63c90"
      password: "{cipher}e2b85d7788b9f4330a8a552026592f5e2f2003475abd19d97971145f5b2da72558ad63bd423c9cb80d8d88f41a434189"
      driver-class-name: com.mysql.cj.jdbc.Driver
    feed:
      url: jdbc:mysql://qua-rdb/feed_db
      username: "{cipher}876532613553ec861fdad2a10e7f4be2682e0845b8513d2ed09f5b9f34f63c90"
      password: "{cipher}e2b85d7788b9f4330a8a552026592f5e2f2003475abd19d97971145f5b2da72558ad63bd423c9cb80d8d88f41a434189"
      driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      contest:
        uri: "${mongodb.encrypted-uri}${mongodb.qua_contest}"
        dbname: qua_contest
        auto-index-creation: true
      utility:
        uri: "${mongodb.encrypted-uri}${mongodb.qua_util}"
        dbname: qua_util
        auto-index-creation: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  kafka:
    bootstrap-servers: kafka-primary:19092,kafka-secondary:19092,kafka-backup:19092

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8516/eureka/
