Server:
  port: 25680

spring:
  application:
    name: batch-service

mongodb:
  encrypted-uri: "{cipher}a517cc0cd2e3d64f9a4a9ae03d15743aab0aca07131f9aebe85219010a2d50ff78e4590f7da8bcd516bbc04e3da3fa7d04dfb32012c7a01d4a5f92b18950122b178f28943790e0eda5eb9e14f0b05013"
  qua_util: "/local_qua_util?authSource=admin"
  qua_contest: "/local_qua_contest?authSource=admin"

  dataSource:
    contest:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/contest?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1q2w3e4r
    feed:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/feed?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1q2w3e4r

  data:
    mongodb:
      contest:
        uri: "${mongodb.encrypted-uri}${mongodb.qua_contest}"
        dbname: qua_contest
        auto-index-creation: true
      utility:
        uri: "${mongodb.encrypted-uri}${mongodb.qua_util}"
        dbname: qua_util
        auto-index-creation: true

    redis:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
      host: "{cipher}ca9a8f9c2411856993261468371f76cb789d803b3a1d799310535dc72e03281a"
      port: 7379
      password: "{cipher}710142fef4d9b369d5d250abad029544616dae3b0237c2fedf059b0af60a27c5"

  kafka:
    bootstrap-servers: "{cipher}a0ea7fa7614decbb52dca73ba151276b0038ab37fb82fcc63776a2bb407b8a9954ad6c97c9e9e7d65cbc442e9210e829675f016cbe2d9311b1a657dd1abe312b6691fd7b4341e1310f83061909ca44be"
    consumer:
      group-id: batch-group

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8516/eureka/