Server:
  port: 27675

mongodb:
  encrypted-uri: "{cipher}a517cc0cd2e3d64f9a4a9ae03d15743aab0aca07131f9aebe85219010a2d50ff78e4590f7da8bcd516bbc04e3da3fa7d04dfb32012c7a01d4a5f92b18950122b178f28943790e0eda5eb9e14f0b05013"
  base: "/contest_read_db?replicaSet=rs0&authSource=admin"

spring:
  application:
    name: contest-read-service

  data:
    mongodb:
      uri: "${mongodb.encrypted-uri}${mongodb.base}"
      auto-index-creation: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  kafka:
    bootstrap-servers: kafka-primary:19092,kafka-secondary:19092,kafka-backup:19092
    consumer:
      group-id: contest-read-group
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8516/eureka/
