import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { CommonLayout } from "@/components/common/molecules";
import { CommonGbnb } from "@/components/common/organisms";
import "@repo/ui/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-center">
          <CommonLayout.Container>
            {children}
            <CommonGbnb />
          </CommonLayout.Container>
        </div>
      </body>
    </html>
  );
}
