import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { CommonLayout } from "@/components/common/molecules";
import "@repo/ui/styles.css";
import QueryClientProvider from "@/components/common/molecules/QueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider>
          <div className="flex justify-center h-full">
            <CommonLayout.Container className="bg-white h-full">
              {children}
            </CommonLayout.Container>
          </div>
        </QueryClientProvider>
      </body>
    </html>
  );
}
