import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CommonLayout } from "../components/common/molecules/CommonLayout";
import CommonGbnb from "../components/common/organisms/CommonGbnb";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Turborepo",
	description: "Generated by create turbo",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}): JSX.Element {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex justify-center">
					<CommonLayout.Container>
						{children}
						<CommonGbnb />
					</CommonLayout.Container>
				</div>
			</body>
		</html>
	);
}
