import type { Metadata } from 'next';
import { CommonGbnb } from '@/components/common/organisms';

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <>
      {children}
      <CommonGbnb />
    </>
  );
}
