import type { ContentsStatistics, Shorts } from "@/types/contents";
import type { Member } from "@/types/member";

const author: Member = {
  memberUuid: "tvhesuinbada4267",
  nickname: "해수인tv yellow aquarium",
  grade: "백만 유튜버",
  profileImageUrl: "/dummies/members/tvhesuinbada4267.jpg",
};
const statistics: ContentsStatistics = {
  likeCount: 543897,
  dislikeCount: 543897,
  commentCount: 543897,
  hitCount: 543897,
};

export const SHORTS_LIST_DATA = [
  "shorts-001",
  "shorts-002",
  "shorts-003",
  "shorts-004",
  "shorts-005",
];

export const SHORTS_DATA: Record<string, Shorts> = {
  "shorts-001": {
    author,
    statistics,
    shortsUuid: "shorts-001",
    title: "폭망한 어항에 새우 1000마리를 넣으면 생기는 일!!",
    content: "",
    mediaUrl: "/dummies/medias/shorts-001.mp4",
    playtime: 49,
    hashtags: [{ name: "수초어항" }],
    createdAt: "2023-12-06 12:00:00",
    updatedAt: "2023-12-06 12:00:00",
  },
  "shorts-002": {
    author,
    statistics,
    shortsUuid: "shorts-002",
    title: "산호를 650일 키우면 생기는 일!",
    content: "목을 친 산호는 '레더'라는 산호입니다^^",
    mediaUrl: "/dummies/medias/shorts-002.mp4",
    playtime: 46,
    hashtags: [{ name: "산호" }],
    createdAt: "2023-12-21 12:00:00",
    updatedAt: "2023-12-21 12:00:00",
  },
  "shorts-003": {
    author,
    statistics,
    shortsUuid: "shorts-003",
    title: "꼬리가 썩어가는 가시복어에게 후시딘을 발라주면 생기는 일!",
    content:
      "물고기가 상처가 나면 후시딘을 발라주는데, 밥 잘 먹고 상태가 양호한 물고기에게만 발라 줘야 합니다. 만약 물고기 체력이 안되면 쇼크사 할 수 있으니 주의가 필요하네요. 가시복어에게 후시딘과 오라메디를 섞어서 발라줬는데, 오라메디를 섞어준 이유는 후시딘만 바르면 물에 다 씻겨 내려가네요. 그래서 물속에서도 잘 붙어 있으라고 섞어줬습니다^^",
    mediaUrl: "/dummies/medias/shorts-003.mp4",
    playtime: 55,
    hashtags: [{ name: "해수어키우기" }],
    createdAt: "2023-11-15 12:00:00",
    updatedAt: "2023-11-15 12:00:00",
  },
  "shorts-004": {
    author,
    statistics,
    shortsUuid: "shorts-004",
    title: "집에서 성게를 키우면 생기는일 ㅋㅋ",
    content:
      "짧게 성게 영상을 만들어 봤습니닷!!^^ 성게는 미역이나 해조류를 뜯어 먹고 사는 야행성 동물인데, 수조 내에서는 돌에 붙어 있는 보라색 알게를 뜯어 먹고 삽니다. 이 녀석 아주 깨끗하게 싹 뜯어 먹어요.. 그런데 ㅋㅋ 자꾸 머리에 뭘 붙이고 다니네요 ㅋㅋ",
    mediaUrl: "/dummies/medias/shorts-004.mp4",
    playtime: 57,
    hashtags: [{ name: "해수어키우기" }, { name: "성게키우기" }],
    createdAt: "2023-07-06 12:00:00",
    updatedAt: "2023-07-06 12:00:00",
  },
  "shorts-005": {
    author,
    statistics,
    shortsUuid: "shorts-005",
    title: "어항속 손모양에 대해 질문하시는 분들이 많아 알려드립니다",
    content: "",
    mediaUrl: "/dummies/medias/shorts-005.mp4",
    playtime: 59,
    hashtags: [
      { name: "복어" },
      { name: "돌돔" },
      { name: "동물" },
      { name: "생물" },
      { name: "물고기" },
      { name: "가재" },
      { name: "reef" },
      { name: "구피" },
      { name: "열대어키우기" },
      { name: "문어" },
      { name: "새우" },
      { name: "octopus" },
      { name: "animal" },
      { name: "랍스터" },
      { name: "수초어항" },
      { name: "바다" },
      { name: "해양생물" },
      { name: "오징어" },
      { name: "취미생활" },
      { name: "애완동물" },
      { name: "반려동물" },
      { name: "어항꾸미기" },
      { name: "수조만들기" },
      { name: "킹크랩" },
      { name: "광어" },
      { name: "우럭" },
      { name: "쭈꾸미" },
      { name: "생선" },
      { name: "낚시" },
      { name: "아쿠아리움" },
      { name: "고래" },
      { name: "강" },
      { name: "민물고기" },
      { name: "상어" },
      { name: "우파루파" },
      { name: "테라리움만들기" },
      { name: "하천" },
      { name: "개울" },
      { name: "가오리" },
      { name: "생이새우" },
      { name: "고등어" },
      { name: "갈치" },
      { name: "산호키우기" },
      { name: "여과기" },
      { name: "여과재" },
      { name: "꽃게" },
      { name: "참돔" },
      { name: "블루탱" },
      { name: "옐로우탱" },
      { name: "고비" },
      { name: "군소" },
      { name: "이끼" },
      { name: "붕어" },
      { name: "잉어" },
      { name: "강성돔" },
      { name: "벵에돔" },
      { name: "디스커스" },
      { name: "참게" },
      { name: "레고" },
      { name: "딸기" },
      { name: "투구게" },
      { name: "고구마" },
      { name: "타조알" },
      { name: "니모" },
      { name: "곰치" },
      { name: "말미잘" },
      { name: "탈피" },
      { name: "흰다리새우" },
      { name: "성게" },
      { name: "성게알" },
      { name: "멍게" },
      { name: "굴" },
      { name: "홍합" },
      { name: "모시조게" },
      { name: "바지락" },
      { name: "개불" },
      { name: "전복" },
      { name: "기생충" },
      { name: "해삼" },
    ],
    createdAt: "2024-08-27 12:00:00",
    updatedAt: "2024-08-27 12:00:00",
  },
};
