server:
  port: 25678

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb+srv://kyeong:GyJ6y2p45eFLOTak@mulmeongcluster.xtkii.mongodb.net/notification_db?retryWrites=true&w=majority&appName=mulmeongcluster
      auto-index-creation: true

  kafka:
    bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
    consumer:
      group-id: notification-group

  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8516/eureka/

api:
  member-read-service:
    url: https://api.qua.world/member-read-service/v1
  comment-service:
    url: https://api.qua.world/comment-service/v1
  feed-read-service:
    url: https://api.qua.world/feed-read-service/v1
  shorts-read-service:
    url: https://api.qua.world/shorts-read-service/v1
