import type { Metadata } from "next";
import "@/app/globals.css";
import "@repo/ui/styles.css";
import { CommonHeader } from "@/components/common/molecules";
import { CommonGbnb } from "@/components/common/organisms";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <>
      <CommonHeader>채팅리스트</CommonHeader>
      {children}
      <CommonGbnb />
    </>
  );
}
