server:
  port: 25672
  
mongodb:
  encrypted-uri: "{cipher}4c2437e12cbac1fef39e51d77da52ea9dd382f1c1c649d9789d66fac09e4e1c2ce4c6ee79d334720467789bac81caabae5fc9ebf82212192687bd30a70960f54aa467e6512e1d25943b7b6561914d10d4f3cf8a8c3eb410652bfa0e7490267f0"
  base: "/utility_db?replicaSet=rs0&authSource=admin"
  
spring:
  application:
    name: utility-service
    
  data:
    mongodb:
      uri: "${mongodb.encrypted-uri}${mongodb.base}"
      auto-index-creation: true
      
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8516/eureka/
