server:
  port: 25678

mongodb:
  encrypted-uri: "{cipher}a517cc0cd2e3d64f9a4a9ae03d15743aab0aca07131f9aebe85219010a2d50ff78e4590f7da8bcd516bbc04e3da3fa7d04dfb32012c7a01d4a5f92b18950122b178f28943790e0eda5eb9e14f0b05013"
  base: "/notification_db?authSource=admin"

spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: "${mongodb.encrypted-uri}${mongodb.base}"
      auto-index-creation: true

  kafka:
    bootstrap-servers: "{cipher}a0ea7fa7614decbb52dca73ba151276b0038ab37fb82fcc63776a2bb407b8a9954ad6c97c9e9e7d65cbc442e9210e829675f016cbe2d9311b1a657dd1abe312b6691fd7b4341e1310f83061909ca44be"
    consumer:
      group-id: notification-group

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8516/eureka/
      
api:
  member-read-service:
    url: https://api.qua.world/member-read-service/v1
  comment-service:
    url: https://api.qua.world/comment-service/v1
  feed-read-service:
    url: https://api.qua.world/feed-read-service/v1
  shorts-read-service:
    url: https://api.qua.world/shorts-read-service/v1