Server:
  port: 25673
  
spring:
  application:
    name: comment-service

  DataSource:
    url: jdbc:mysql://localhost:3306/comment_db
    username: root
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: "{cipher}a0ea7fa7614decbb52dca73ba151276b0038ab37fb82fcc63776a2bb407b8a9954ad6c97c9e9e7d65cbc442e9210e829675f016cbe2d9311b1a657dd1abe312b6691fd7b4341e1310f83061909ca44be"

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8516/eureka/
