import type { Metadata } from "next";
import "@/app/globals.css";
import "@repo/ui/styles.css";
import CategoryHeader from "@/components/feed-tab/organisms/CategoryHeader";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <>
      <CategoryHeader />
      {children}
    </>
  );
}
