import type { Metadata } from "next";
import { CommonGbnb } from "@/components/common/organisms";
import InnerMobileContainer from "@/components/layouts/InnerMobileContainer";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <InnerMobileContainer>
      {children}
      <CommonGbnb />
    </InnerMobileContainer>
  );
}
